# Generated by Django 5.2.3 on 2026-06-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address / Suburb')),
                ('ndis_number', models.CharField(blank=True, max_length=50, verbose_name='NDIS Number')),
                ('plan_management', models.CharField(blank=True, choices=[('NDIA Agency Managed', 'NDIA Agency Managed'), ('Self Managed', 'Self Managed'), ('Plan Managed', 'Plan Managed'), ('Not Yet Approved', 'Not Yet Approved'), ('Not Sure', 'Not Sure')], max_length=50, verbose_name='Plan Managed By')),
                ('support_goals', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('referrer_name', models.CharField(blank=True, max_length=150)),
                ('relationship', models.CharField(blank=True, choices=[('Self', 'Self'), ('Family Member', 'Family Member'), ('Support Coordinator', 'Support Coordinator'), ('Healthcare Provider', 'Healthcare Provider'), ('Other', 'Other')], max_length=50)),
                ('referrer_phone', models.CharField(blank=True, max_length=20)),
                ('referrer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_required', to='referrals.referral')),
            ],
        ),
    ]
