# Generated by Django 6.0.6 on 2026-06-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_assigned_staff_alter_referral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='migration_test_field',
            field=models.CharField(blank=True, help_text='Added to test PostgreSQL migration', max_length=50, null=True),
        ),
    ]
