# Generated by Django 6.0.6 on 2026-06-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referral_migration_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='migration_test_field',
        ),
    ]
