# Generated by Django 5.2.3 on 2026-07-02 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_remove_referral_migration_test_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='assigned_staff',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='ndis_number',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='plan_management',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_email',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_phone',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='support_goals',
        ),
        migrations.AddField(
            model_name='referral',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='referrals/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='behaviour_support_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='consent_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='current_medication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='current_situation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='referral',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referral',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='primary_disability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referral',
            name='requested_services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='risk_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='urgency',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
