# Generated by Django 5.2.3 on 2026-06-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_alerts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurring',
            field=models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='support_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
