# Generated by Django 5.2.3 on 2026-06-30 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_appointment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_required', models.TextField(blank=True, null=True)),
                ('participant_goals', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(default='Weekly', max_length=50)),
                ('preferred_days', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=100, null=True)),
                ('hours_per_visit', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medication_notes', models.TextField(blank=True, null=True)),
                ('behaviour_alerts', models.TextField(blank=True, null=True)),
                ('emergency_instructions', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Review Due', 'Review Due'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to='dashboard.supportworker')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_plans', to='dashboard.participant')),
            ],
        ),
    ]
